### ISSUE TITLE
Overlapping of "grouped" shapes

### ISSUE THREAD

**Issue by richterb** [mapnik/mapnik-support#26]
I am rendering a serie of points, and my stylesheet draws two markers for each point; the idea is to render a "marker" shape (the usual round one you find in Leaflet for example) and an icon inside it.

The stylesheet (in MSS for better readability) looks like this:

``` css
        [marker="true"]::marker {
            marker-file: url('marker.svg');
            marker-allow-overlap: true;
            marker-fill: [color];
            marker-line-color: white;
            marker-line-width: 2;
            marker-height: 40;
            marker-transform: translate(0, @marker-height/-2);
        }
        [marker="true"]::inner-icon {
            marker-file: url(@marker-icon);
            marker-allow-overlap: true;
            marker-height: @marker-icon-height;
            marker-fill: white;
            marker-transform: translate(0, @marker-icon-offset);
        }
```

As far as I understood the various resources I found on the subject, I would have assumed that for the first point, the two markers would be rendered together; then the second point, and so on. However, the result I'm seeing makes me think it is rather rendering the first marker symbol for every point, and then the second for every point:

![screen shot 2014-12-08 at 10 11 30](https://cloud.githubusercontent.com/assets/1935200/5376245/e50a8286-8073-11e4-92ff-ac1d7aa46a47.png)

I'm using Mapnik trunk, using a MemoryDatasource (each point is a mapnik.Feature), and the AGG renderer. 

Is this the expected behavior, and if so, do you have any idea on how to achieve overlapping markers?

Thank you :)
